site_name: Notas Musicais
repo_url: https://github.com/faahiero/notas-musicais
repo_name: faahiero/notas-musicais
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/music-ico.png
  favicon: assets/music-ico.png

markdown_extensions:
  - attr_list


extra_css:
  - stylesheets/extra.css